/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Home extends javax.swing.JFrame {

    public int i = 0;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnAddNewPatient = new javax.swing.JButton();
        btnAddDiagnossInfo = new javax.swing.JButton();
        btnHistoryPatient = new javax.swing.JButton();
        btnUpdatePatient = new javax.swing.JButton();
        btnHospitalInfo = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/HMS ICON/two arrow.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(240, 59));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 29, 81, -1));

        btnAddNewPatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAddNewPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/HMS ICON/add new patient.png"))); // NOI18N
        btnAddNewPatient.setText("Add New Patient Record");
        btnAddNewPatient.setPreferredSize(new java.awt.Dimension(240, 59));
        btnAddNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddNewPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 114, 300, -1));

        btnAddDiagnossInfo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAddDiagnossInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/HMS ICON/add diag.png"))); // NOI18N
        btnAddDiagnossInfo.setText("Add Diagnoss Information");
        btnAddDiagnossInfo.setPreferredSize(new java.awt.Dimension(240, 59));
        btnAddDiagnossInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiagnossInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddDiagnossInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 191, 300, -1));

        btnHistoryPatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnHistoryPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/HMS ICON/rsz_history1.png"))); // NOI18N
        btnHistoryPatient.setText("Full History of the Patient");
        btnHistoryPatient.setPreferredSize(new java.awt.Dimension(240, 59));
        btnHistoryPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryPatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistoryPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 268, 300, -1));

        btnUpdatePatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnUpdatePatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/HMS ICON/rsz_update_details.png"))); // NOI18N
        btnUpdatePatient.setText("Update Patient Record");
        btnUpdatePatient.setPreferredSize(new java.awt.Dimension(240, 59));
        btnUpdatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdatePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 345, 300, -1));

        btnHospitalInfo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnHospitalInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/HMS ICON/rsz_hospital_information.png"))); // NOI18N
        btnHospitalInfo.setText("Hospital Information");
        btnHospitalInfo.setPreferredSize(new java.awt.Dimension(240, 59));
        btnHospitalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnHospitalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 422, 300, -1));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/HMS ICON/exit.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setPreferredSize(new java.awt.Dimension(240, 59));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 499, 300, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/HMS ICON/home.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "<html><b style=\"color:red;\">Do you really want to close Application</b></html>", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (i == 0) {
            btnAddNewPatient.setLocation(90, 30);
            btnAddDiagnossInfo.setLocation(393, 30);

            btnHistoryPatient.setLocation(696, 30);
            btnUpdatePatient.setLocation(999, 30);
            btnHospitalInfo.setLocation(696, 89);
            btnLogout.setLocation(999, 89);
            i = 1;
        } else {
            btnAddNewPatient.setLocation(10, 107);
            btnAddDiagnossInfo.setLocation(10, 184);

            btnHistoryPatient.setLocation(10, 261);
            btnUpdatePatient.setLocation(10, 338);
            btnHospitalInfo.setLocation(10, 415);
            btnLogout.setLocation(10, 490);
            i = 0;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPatientActionPerformed
        // TODO add your handling code here:
new AddNewPatient().setVisible(true);
    }//GEN-LAST:event_btnAddNewPatientActionPerformed

    private void btnAddDiagnossInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiagnossInfoActionPerformed
        // TODO add your handling code here:
new AddDignossInfo().setVisible(true);
    }//GEN-LAST:event_btnAddDiagnossInfoActionPerformed

    private void btnHistoryPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryPatientActionPerformed
        // TODO add your handling code here:
new FullHistoryOfPatient().setVisible(true);
    }//GEN-LAST:event_btnHistoryPatientActionPerformed

    private void btnUpdatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePatientActionPerformed
        // TODO add your handling code here:
new UpdatePatientRecord().setVisible(true);
    }//GEN-LAST:event_btnUpdatePatientActionPerformed

    private void btnHospitalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalInfoActionPerformed
        // TODO add your handling code here:
new HospitalInfo().setVisible(true);
    }//GEN-LAST:event_btnHospitalInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDiagnossInfo;
    private javax.swing.JButton btnAddNewPatient;
    private javax.swing.JButton btnHistoryPatient;
    private javax.swing.JButton btnHospitalInfo;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdatePatient;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
